name: 'License Check'
description: 'Check there is a license file in each custom module directory'
inputs:
  namespaces:  # Module namespaces to check
    description: 'Comma separated list of namespaces'
    required: true
runs:
  using: 'node12'
  main: 'index.js'