name: 'License Check'
description: 'Check there is a license file in each custom module directory'
inputs:
  namespaces:  # Module namespaces to check
    description: 'Comma separated list of namespaces'
    required: true
  auto_generate:
      description: Automatically generate and commit missing license files (true / false)
      required: false
      default: false
runs:
  using: 'node12'
  main: 'index.js'